apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: onlinestoreapi
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: onlinestoreapi
    spec:
      #hostNetwork: true
      containers:
        - image: "rafaelc/rpi-storeapi"
          imagePullPolicy: Always
          name: onlinestoreapi
          ports:
            - containerPort: 80
              hostPort: 8040
